# Generated by Django 3.0.6 on 2020-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='opposition',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='area',
            name='winner',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
