# Generated by Django 3.0.6 on 2020-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200514_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='opposition_party',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='winning_party',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
